apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  labels:
    app: kafka
  name: robipozzi-kafka
  namespace: openshift-operators
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      inter.broker.protocol.version: '2.7'
      log.message.format.version: '2.7'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: tls
        port: 9092
        tls: true
        type: route
      - name: tlsauth
        authentication:
          type: tls
        port: 9093
        tls: true
        type: route
    replicas: 3
    storage:
      type: ephemeral
    version: 2.7.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral